### ISSUE TITLE
Font awsome css not there in app.css

### ISSUE THREAD

**Issue by rameshtyaga** [code-lever/font-awesome-phoenix#1]
Hi @nickveys ,

Thanks for the plugin, 

After did the following two things,

```
Add font_awesome_phoenix to your list of dependencies in mix.exs:

def deps do
  [{:font_awesome_phoenix, "~> 0.1"}]
end

Add the HTML module to your web.ex to make it available to your templates:

def view do
  ...
  import FontAwesomePhoenix.HTML
end
```

The helper method generates html

`<%= fa_icon("globe") %>`

`<i class="fa fa-globe"></i>`

But there is no font-awsome css code on app.css file

Did i miss anything?

**Comment by nickveys** [comment]
You didn't miss anything. Phoenix has no asset pipeline like Rails does, so bundling the CSS didn't seem to provide much value. If there is a good way to do it I'd gladly add it but just putting the CSS in here adds an unnecessary maintenance burden unless it is doing something useful.

**Comment by rameshtyaga** [comment]
Ohh, it's ok @nickveys , better we can add this to readme file as well
